### PR TITLE
Change org logo helptext

### PR DESCRIPTION
**Pull request by Bhavatu**
Change organization logo helptext

Asana: https://app.asana.com/0/1206017643443542/1208090959630308

### CODE REVIEW

**Comment by MWargelin** [comment]
Looks fine :+1: However, I'm not sure what is the process/policy with translations. The help text is now only available in English, should it be translated to other languages?

**Comment by tituomin** [comment]
> Looks fine 👍 However, I'm not sure what is the process/policy with translations. The help text is now only available in English, should it be translated to other languages?

@MWargelin Our Weblate does not support translations within a PR branch (and that would also often lead to difficult merge conflicts) so we usually translate after merging to main

**Review by MWargelin — APPROVED** [review]

**Comment by MWargelin** [comment]
> > Looks fine 👍 However, I'm not sure what is the process/policy with translations. The help text is now only available in English, should it be translated to other languages?
> 
> @MWargelin Our Weblate does not support translations within a PR branch (and that would also often lead to difficult merge conflicts) so we usually translate after merging to main

Ok thanks, good to know, I'll approve then :) @Bhavatu if schedules allow it would be useful if I could be there once you do the translations, I'd like to see how it's done!

**Comment by Bhavatu** [comment]
> > > Looks fine 👍 However, I'm not sure what is the process/policy with translations. The help text is now only available in English, should it be translated to other languages?
> > 
> > 
> > @MWargelin Our Weblate does not support translations within a PR branch (and that would also often lead to difficult merge conflicts) so we usually translate after merging to main
> 
> Ok thanks, good to know, I'll approve then :) @Bhavatu if schedules allow it would be useful if I could be there once you do the translations, I'd like to see how it's done!

Sure :+1: . Let's do it tomorrow at some point!

**Pull request merged**
